server.port=8081
spring.application.name=api
spring.datasource.url=jdbc:mysql://localhost:3306/barbearia_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
# Configuracoes do Spring Mail (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yyanngoncalves@gmail.com
spring.mail.password=sfdofrjmzoxovkfd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true